"""Turning generated pages into things outside this program: JSON, SQL, a digest.

The SQL targets the schema in `docs/schema.sql` directly. It refuses to load on
top of a level that already has pages, because pages are frozen once published
and loading over them is never what anyone meant.
"""

from __future__ import annotations

import hashlib
import json
from typing import Any, Sequence

from .generate import Page
from .template import Level, band_sources


def as_dict(level: Level, pages: Sequence[Page]) -> dict[str, Any]:
    return {
        "level": level.name,
        "sort_order": level.sort_order,
        "description": level.description,
        "page_count": level.page_count,
        "default_packet_size": level.default_packet_size,
        "bands": band_sources(level.bands),
        "pages": [
            {
                "page_number": page.page_number,
                "problems": [
                    {
                        "position": problem.position,
                        "prompt": problem.prompt,
                        "correct_answer": problem.correct_answer,
                        "answer_shape": problem.answer_shape,
                    }
                    for problem in page.problems
                ],
            }
            for page in pages
        ],
    }


def canonical_json(level: Level, pages: Sequence[Page]) -> str:
    """Stable JSON: sorted keys, no incidental whitespace. Safe to hash."""
    return json.dumps(
        as_dict(level, pages), sort_keys=True, separators=(",", ":"), ensure_ascii=False
    )


def digest(level: Level, pages: Sequence[Page]) -> str:
    return hashlib.sha256(canonical_json(level, pages).encode("utf-8")).hexdigest()


def pretty_json(level: Level, pages: Sequence[Page]) -> str:
    return json.dumps(as_dict(level, pages), indent=2, ensure_ascii=False) + "\n"


def _quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def _jsonb(value: Any) -> str:
    return _quote(json.dumps(value, sort_keys=True, separators=(",", ":"))) + "::jsonb"


def sql(level: Level, pages: Sequence[Page], *, published: bool = True) -> str:
    name = _quote(level.name)
    lines: list[str] = []
    add = lines.append

    problem_count = sum(len(page.problems) for page in pages)

    add("-- ---------------------------------------------------------------------------")
    add(f"-- Level {level.name} — {level.description}")
    add(f"-- {len(pages)} pages, {problem_count} problems, generated from the band seeds.")
    add("--")
    add("-- Generated by `python -m curriculum generate`. Do not hand-edit: the seeds in")
    add("-- page_templates are what make a frozen page reproducible, and an edit here")
    add("-- silently breaks that.")
    add("-- ---------------------------------------------------------------------------")
    add("")
    add("BEGIN;")
    add("")
    add("-- Pages are frozen once published. Refuse to load on top of existing ones")
    add("-- rather than quietly giving a repeating student different problems.")
    add("DO $$")
    add("BEGIN")
    add("    IF EXISTS (")
    add("        SELECT 1 FROM pages p JOIN levels l ON l.id = p.level_id")
    add(f"        WHERE l.name = {name}")
    add("    ) THEN")
    add(
        f"        RAISE EXCEPTION 'level % already has pages; refusing to load over "
        f"published curriculum', {name};"
    )
    add("    END IF;")
    add("END $$;")
    add("")

    add("INSERT INTO levels (name, sort_order, description, default_packet_size, page_count)")
    add(
        f"VALUES ({name}, {level.sort_order}, {_quote(level.description)}, "
        f"{level.default_packet_size}, {level.page_count})"
    )
    add("ON CONFLICT (name) DO UPDATE SET")
    add("    sort_order          = EXCLUDED.sort_order,")
    add("    description         = EXCLUDED.description,")
    add("    default_packet_size = EXCLUDED.default_packet_size,")
    add("    page_count          = EXCLUDED.page_count;")
    add("")

    for band in level.bands:
        add(
            "INSERT INTO page_templates (level_id, page_from, page_to, problems_per_page, "
            "form, operands, constraints, seed)"
        )
        add(
            f"SELECT id, {band.page_from}, {band.page_to}, {band.problems_per_page}, "
            f"{_quote(band.form_spec)},"
        )
        add(f"       {_jsonb(dict(band.operands))},")
        add(f"       {_jsonb(list(band.constraint_sources))},")
        add(f"       {band.seed}")
        add(f"FROM levels WHERE name = {name};")
        add("")

    add("-- Pages go in unpublished so their problems can be attached. Publishing is the")
    add("-- last statement in the transaction, and it is what freezes them.")
    add("INSERT INTO pages (level_id, page_number, template_id, published, published_at)")
    add("SELECT l.id, v.page_number, t.id, false, NULL")
    add("FROM (VALUES")
    page_values = ",\n".join(f"    ({page.page_number})" for page in pages)
    add(page_values)
    add(") AS v(page_number)")
    add("CROSS JOIN levels l")
    add("JOIN page_templates t")
    add("  ON t.level_id = l.id AND v.page_number BETWEEN t.page_from AND t.page_to")
    add(f"WHERE l.name = {name};")
    add("")

    for page in pages:
        add("INSERT INTO problems (page_id, position, prompt, correct_answer, answer_shape)")
        add("SELECT p.id, v.position, v.prompt, v.correct_answer, v.answer_shape")
        add("FROM pages p")
        add("JOIN levels l ON l.id = p.level_id")
        add("CROSS JOIN (VALUES")
        rows = ",\n".join(
            f"    ({problem.position}, {_quote(problem.prompt)}, "
            f"{_quote(problem.correct_answer)}, {_quote(problem.answer_shape)})"
            for problem in page.problems
        )
        add(rows)
        add(") AS v(position, prompt, correct_answer, answer_shape)")
        add(f"WHERE l.name = {name} AND p.page_number = {page.page_number};")
        add("")

    if published:
        add("-- Seal them. After this the freeze trigger rejects any change to these pages")
        add("-- or their problems, which is what makes a repeated packet a repeat.")
        add("UPDATE pages p")
        add("SET published = true, published_at = now()")
        add("FROM levels l")
        add(f"WHERE l.id = p.level_id AND l.name = {name} AND p.published = false;")
        add("")

    add("COMMIT;")
    add("")
    return "\n".join(lines)
